# Generated by Django 2.2.3 on 2019-08-05 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.TextField()),
                ('testid', models.TextField()),
                ('automatable_reason', models.TextField()),
                ('testscript', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testcases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='execute.Selected')),
            ],
        ),
    ]
