# Generated by Django 2.2.3 on 2019-08-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execute', '0002_credentials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credentials',
        ),
    ]
